kind: Deployment
apiVersion: apps/v1
metadata:
  name: toy-moderation-deployment
  labels:
    app: toy-moderation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toy-moderation
  template:
    metadata:
      labels:
        app: toy-moderation
    spec:
      containers:
        - name: toy-moderation
          image: sniper7137/toy-moderation:latest
          ports:
            - containerPort: 5678

---

kind: Service
apiVersion: v1
metadata:
  name: toy-moderation-service
spec:
  selector:
    app: toy-moderation
  ports:
    - protocol: TCP
      port: 5678

---

kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: toy-moderation-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - localhost
    secretName: toy-moderation-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /forum_post
        backend:
          serviceName: toy-moderation-service
          servicePort: 5678